// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.equinux.mattermost-plugin-video-reencode",
  "name": "Video Re-Encode Plugin",
  "description": "Automatically re-encodes video uploads to be compatible with most clients.",
  "version": "0.1.3",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "CreatePreviewImage",
        "display_name": "Create Preview Image",
        "type": "bool",
        "help_text": "Extract a preview image from the video.",
        "placeholder": "",
        "default": false
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
